language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: IDmtsA8DZZhZoRkpDHnspPndClMxDiJeysfKRNd+uiZWG5HHSQSwOVLRJ9VvEMvPwjPbNpc6r1JYUjBCRXdGyQIqS7HQe4nEUUGY1xZcybIHUSplSOZEc8kKQpvC88hE4+QnpOwWAsEH34isgPDby6ODLbXeA2i0Ev4JFsX2le+nE6W5BYFsknRh4SvdFpQw1KH4eFt3Cbixpv/aI9ppZZeoB6ZY/kKxqug15j0k846nETtnnTipucbo5T4CidGMhxpziCGrLcAx/M8giUVted4sYz9nSNyhjaUb3v5hdDDFFg5WpFs2STelEylFbUYjpeOlffud4B/w/gQV8mhtNbajLqlVcRkH2MzbvWmczQB6G2ZwXF2yGtfu7AkSKr2IuxELdfAhylSASnYQuDey1FAMS0lmSFgtqPMDcyxlZEf9XnWK46R7t+QUor/AIffA9MMkC0rYHL23Wa3pR863I6Aa0LxPWAUZlRehhQIOf8kiwEoyur4icOlv2ECK8DjKuBHVjQmMTTSgG1K0+1UV5SeKK+1DtBd3L4xCQKJ7LcFDdvp/uCmVszohxF0HymufaH5C9Z+vAmD9lnzczyCEnSmfjloMEqGgdRk84tVnuQT9tIoxFiIiKon3FrvdsWMRSizVGaK1z5xjJkX9A9FYhMTM3zf+7aeeDe7E9TV8PX8=
  app: pure-lowlands-37491
  on:
    branch: main
