language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iEk3wbS+EIEoHSKNobp2vaCwHfuRVOpL0WT5CFHcRlqOoQxs5W9oXy62GI/oIV2YMzTPgw34xJ8lX70bZsA9032P+OvrXkuV5+GjtKNE6iBbPh5BVAxxWBsT4vZvygaKsyFRLI/FDd2qqjN091CzJajBELkVT0M1JEOIZxLto/Yn1y4cAEJyEOdNurVksTJcsdpPzZpciGMnI2qaosYheVFwK+KJ+WPsI9gu68EcJl5T2M9nKug4IHIirBU04mvCNVOx3qxAYLCj1dBAI9AFzUfbLq9/63qLE4vrki//Gb70ARdlrhQ6sbRoue+KHt4e7yMjc9O69LeDuvGyhwQOjIXnsGepoNU/nswEJcZK1OR+3eMgRCrk0H7O7OVloaxxcr79CPRQVswfpJrpd6eP5pdPX0wbt8Vpnfokt9MULq0uADc/pKn+WmungtyUaKAwijBExjgI7rV+pJGmLYdES86oTFGtiRgUCdwTnp6g1xgOW7cTNKZhyp+FPRY3xJhyMHISAG40ddruqRtuVazXSkoXj3bYOMKd9CPNlyLOmT2UnTT0gvWxL/4FOBuPmPy7RRVJbTrey0E8AJ0j+NUjxoHVjGKezqe2MTzoXqzIse2Fp+vdkSXwjb69LAJjBwz5NdaeZ9zypV6dCoa9f3M80/XRocWO7j9Hog0ltt3BP7U=
  app: pure-lowlands-37491
  on:
    branch: main
  skip_cleanup: true
