language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Fqa9GwNYyxiMNyrtt4Tbm+AjYTbCgSBdDOflBqSzDzlRK0bv+OwDSTa96y+MtyVyE+oI2bVCRBmVcxBpKIjDiKdACQUrhlpISbOswSn5tghbWjNt4h+GYA8IBy8Z/zLedFOSbaYPkBi7SOBkeA45df397kNsBlKkNsmCnwPC6caBQXpevcRCjOnlFWmh81p4s6Ohd9GhdF1cCOBfxNpR6UGwKNAnZD69CQNt5j5EqLZc4pIzQDzjn9o6Fg+v1OeVZoNeH4hsW1cKz1VX2IUkDHwgZ0ZCuU/TLRklGWPb3IT2mvQey09sXbuYeol/UE/k1cMiqoE8XGfAd3nxKYJdyiczLFfjlIV1WoJcaMEpy4YydMBvZDdof+ys1nfe08g9DaL4G+sA8zo9/4wAAIwt4sg49foC4wMb4q8yC78RBdjHAH+YTjXdTzXeWzCV/MYlTaSTR1xcPxbkiKFxwdXTjf61w7ZjZ1JJfCUQDMUea4AR4AXSTusinafW4Sl+Yrn+DIfsFgUKOS3a5/ch1IEXRv+j/F65uuBLKg5mUYbkmJ3AJABmDY7qukszhaNRUCUzS1Jc9n3g1zqK5o01QqvpSDGYdVSGl5sTPDpTC1pGjn8JihKmCfeAf3RPxG3tOA13ZxdvOLpp5VLqGoH5oPe7htXaJyR34gJY+KQzhnYtjQE=
    app: pure-lowlands-37491
    skip_cleanup: true